### ISSUE TITLE
Do a research - best way to implement database functionality

### ISSUE THREAD

**Issue by wsmaga** [wsmaga/AEII_2020_BD2_Smaga_Narciarstwo#16]
Research the best way to integrate a database to existing frontend application. How to communicate with the database the easiest way? Is there a simpler method than using some global database manager object? Can new entity objects be automatically mapped to new entries in DB?
Please note, that:
- every one of our WPF pages can have access to properties and methods from MainWindow or even Application code-behind
- as of now, our application doesn't implement a kosher MVVM approach and let us have faith that it doesn't need to

**Comment by JChrobak** [comment]
We implement database connection using Entity Framework, and use Repository and Unit Of Work patterns.
