### ISSUE TITLE
Add models, repository interfaces and repositories for entities: LiftUsageHistory and TicketTariff

### ISSUE THREAD

**Issue by wsmaga** [wsmaga/AEII_2020_BD2_Smaga_Narciarstwo#25]
Add a model(if necessary), repository interface and repository classes for LiftUsageHistory and TicketTariff entities.
For an example see ILiftTariffRepository.cs, LiftTariffRepostory.cs and Admin.cs.

**Comment by jakub-borek** [comment]
Szczekierałtuj (check this out) to ktoś i merge
