### ISSUE TITLE
Implement owner's methods

### ISSUE THREAD

**Issue by wsmaga** [wsmaga/AEII_2020_BD2_Smaga_Narciarstwo#26]
Make it actually work with the database.

**Comment by wsmaga** [comment]
This might need to wait for the task with models, repositories and interfaces. The owner will need them implemented first.

**Comment by wsmaga** [comment]
Add 'Owner' class to implement owner's actions as in 'Admin'.

**Comment by JChrobak** [comment]
Both Modify Tariff and Modify Schedule are implemented in ModifiesLiftData class. When creating Owner just inherit the ModifiesLiftData class and change the code behind in the Owner page

**Comment by jakub-borek** [comment]
Done

**Comment by wsmaga** [comment]
Is this task done? Close it if so.
