### ISSUE TITLE
Prepare an installator of our application in Visual Studio

### ISSUE THREAD

**Issue by wsmaga** [wsmaga/AEII_2020_BD2_Smaga_Narciarstwo#49]
Supposedly, Visual Studio is able to generate an installator for our application. Research this and prepare the installator.
The installator should properly install our application on Windows OS(this should be easily achievable using VS) and offer silent setup of local DB or maybe choosing a specified remote DB. Decide which approach is best and implement it.
The installation should be offered in two modes:
1. Production mode
- the application is installed in the OS. Make sure the deployed application has it's all necessary libraries alongside it
- the local DB is set up and connected with our app OR the application is prepared to connect to a specified, working external DB
2. Presentation mode
- same as production mode
- additionally, the DB is populated with test data, so much so that it's possible to view and test all the application's functions properly
- additionally, alongside application files there should be a directory with user's manual(this is made by someone else in a different task) and source code

**Comment by jakub-borek** [comment]
Currently prepared presentation installer
